Name <- c("Jeb", "Donald", "Ted", "Marco", "Carly", "Hillary", "Bernie")
ABC_poll   <- c(  4,      62,      51,    21,      2,        14,       15)
CBS_poll   <- c( 12,      75,      43,    19,      1,        21,       19)
polls <- data.frame(Name, ABC_poll, CBS_poll)
str(polls)
head(polls)
mean_abc <- mean(polls$ABC_poll)
cat("Mean:",mean_abc,"\n")
median_abc <- median(polls$ABC_poll)
cat("Median:",median_abc,"\n")
range_abc <- max(polls$ABC_poll) - min(polls$ABC_poll)
cat("Range of ABC Poll:",range_abc, "\n")
mean_cbs <- mean(polls$CBS_poll)
cat("Mean of CBS:",mean_cbs,"\n")
median_cbs <- median(polls$CBS_poll)
cat("Median of CBS:",median_cbs,"\n")
range_cbs <- max(polls$CBS_poll) - min(polls$CBS_poll)
cat("Range of CBS Poll:",range_cbs, "\n")
range_difference <- (range_abc - range_cbs)
cat("Difference between ranges of ABC and CBS polls:", range_difference, "\n")
range(polls[, c("ABC_poll","CBS_poll")])
polls$Diff <- (polls$CBS_poll - polls$ABC_poll)
cat("Difference between CBS and ABC polls:", polls$Diff, "\n")
install.packages("ggplot2")
library(tidyr)
library(ggplot2)
polls_long <- pivot_longer(polls, cols = c(ABC_poll, CBS_poll),names_to = "Poll", values_to = "Score")
ggplot(polls_long, aes(x = Name, y = Score, fill = Poll)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "ABC vs CBS Poll Results", x = "Candidate", y = "Poll Score") +
  scale_fill_manual(values = c("ABC_poll" = "skyblue", "CBS_poll" = "orange")) +
  theme_minimal()
